# Generated by Django 2.2.1 on 2019-12-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("budget", "0005_budgetsummary_tower")]

    operations = [
        migrations.AddField(
            model_name="tower",
            name="percentage",
            field=models.IntegerField(
                choices=[
                    (0, "0 %"),
                    (1, "10 %"),
                    (20, "20 %"),
                    (30, "30 %"),
                    (40, "40 %"),
                    (50, "50 %"),
                    (60, "60 %"),
                    (70, "70 %"),
                    (80, "80 %"),
                    (90, "90 %"),
                    (100, "100 %"),
                ],
                default=1,
            ),
            preserve_default=False,
        )
    ]
