# Generated by Django 2.2.1 on 2020-01-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("budget", "0006_tower_percentage")]

    operations = [
        migrations.AlterField(
            model_name="tower",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "open"),
                    ("planned", "planned"),
                    ("set", "set"),
                    ("in_progress", "in progress"),
                    ("finished", "finished"),
                    ("on hold", "on hold"),
                ],
                default="open",
                max_length=128,
            ),
        )
    ]
