# Generated by Django 2.2.1 on 2020-02-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0007_auto_20200113_2018"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tower", options={"verbose_name_plural": "Tower"},
        ),
    ]
