# Generated by Django 2.2.4 on 2020-03-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("budget", "0008_auto_20200223_2124")]

    operations = [
        migrations.CreateModel(
            name="QuarterTotal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("quarter", models.PositiveIntegerField()),
                ("amount_pln", models.DecimalField(decimal_places=2, max_digits=8)),
                ("amount_gbp", models.DecimalField(decimal_places=2, max_digits=8)),
                ("amount_usd", models.DecimalField(decimal_places=2, max_digits=8)),
                ("amount_safe", models.DecimalField(decimal_places=2, max_digits=8)),
                ("amount_kejt", models.DecimalField(decimal_places=2, max_digits=8)),
                ("amount_mewash", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date_added", models.DateField(auto_now_add=True)),
                ("note", models.TextField(blank=True, default=None)),
            ],
        )
    ]
