# Generated by Django 2.2.4 on 2020-03-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("budget", "0009_quartertotal")]

    operations = [
        migrations.RemoveField(model_name="quartertotal", name="amount_pln"),
        migrations.AlterField(
            model_name="quartertotal",
            name="amount_gbp",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="quartertotal",
            name="amount_safe",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="quartertotal",
            name="amount_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
